"""
pybind11 example plugin
"""
from __future__ import annotations
import typing
__all__ = ['Layer', 'TwoTuple', 'add', 'get_boundary', 'get_goal', 'get_map', 'get_obstacles', 'get_robot', 'get_start', 'polygon', 'rvg', 'vertex']
class Layer:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, theta_lb: typing.SupportsFloat, theta_ub: typing.SupportsFloat, fineApprox: bool, simplifiedGeometry: bool) -> None:
        ...
    @typing.overload
    def __init__(self, layer: Layer) -> None:
        ...
    def borderIsHole(self) -> bool:
        ...
    def buildVisibilityGraph(self, robot: polygon, border: polygon, obstacles: list[polygon]) -> None:
        ...
    def getEdges(self) -> list[tuple[vertex, vertex]]:
        ...
    def getGrownObs(self) -> list[polygon]:
        ...
    def getHoles(self) -> list[polygon]:
        ...
    def getRobotBBox(self) -> polygon:
        ...
    def getRobotBBoxInverted(self) -> polygon:
        ...
    def getShrinkedBorder(self) -> polygon:
        ...
    def getThetaLb(self) -> float:
        ...
    def getThetaUb(self) -> float:
        ...
    def getVertex(self, index: typing.SupportsInt) -> vertex:
        ...
    def getVisibleAreaPolygon(self, x: typing.SupportsFloat, y: typing.SupportsFloat) -> polygon:
        ...
    def getVisibleAreaPolygons(self) -> dict[vertex, polygon]:
        ...
    def hasHoles(self) -> bool:
        ...
    def isFeasible(self) -> bool:
        ...
    def isVertexOnHole(self, vertex: vertex) -> bool:
        ...
    def legalConfig(self, v: vertex) -> bool:
        ...
class TwoTuple:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: TwoTuple) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def first(self) -> float:
        ...
    @first.setter
    def first(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def second(self) -> float:
        ...
    @second.setter
    def second(self, arg0: typing.SupportsFloat) -> None:
        ...
class polygon:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: polygon) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> vertex:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vertices: list[vertex], center: vertex, sortVertices: bool = False) -> None:
        ...
    @typing.overload
    def __init__(self, vertices: list[vertex], sortVertices: bool = False) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: typing.SupportsInt) -> vertex:
        ...
    def bbox(self) -> polygon:
        ...
    def contains(self, arg0: vertex) -> bool:
        ...
    def convexDecomposition(self) -> list[polygon]:
        ...
    @typing.overload
    def draw(self, arg0: str, arg1: str, arg2: bool) -> None:
        ...
    @typing.overload
    def draw(self, arg0: str, arg1: bool) -> str:
        ...
    def getCentroid(self) -> vertex:
        ...
    def getVertices(self) -> list[vertex]:
        ...
    def getX(self) -> list[float]:
        ...
    def getY(self) -> list[float]:
        ...
    def intersects(self, arg0: polygon) -> bool:
        ...
    def invert(self) -> None:
        ...
    def isConvex(self) -> bool:
        ...
    def merge(self, arg0: polygon) -> polygon:
        ...
    def moveTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    def moveToCopy(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> polygon:
        ...
    @typing.overload
    def rotate(self, arg0: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def rotate(self, arg0: typing.SupportsFloat, arg1: vertex) -> None:
        ...
    @typing.overload
    def rotateCopy(self, arg0: typing.SupportsFloat) -> polygon:
        ...
    @typing.overload
    def rotateCopy(self, arg0: typing.SupportsFloat, arg1: vertex) -> polygon:
        ...
    def scale(self, arg0: typing.SupportsFloat) -> polygon:
        ...
    def size(self) -> int:
        ...
    def translate(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...
class rvg:
    def __init__(self, robot: polygon, border: polygon, obstacles: list[polygon], resolution: typing.SupportsInt, fineApprox: bool, numThreads: typing.SupportsInt, optimal: bool = False, verbose: bool = False) -> None:
        """
        Constructs a VisibilityGraph with the specified parameters.
        """
    def animation(self, figPath: str, title: bool = True) -> None:
        ...
    def debugMaxPropagation(self) -> None:
        ...
    def draw(self, figPath: str, title: bool = True, path: bool = True, graph: bool = True, show: bool = False) -> None:
        ...
    def getAdjacentVertices(self, v: vertex) -> list[vertex]:
        ...
    def getBuildTime(self) -> float:
        ...
    def getEdgeLayersBackward(self) -> list[list[tuple[vertex, vertex]]]:
        ...
    def getEdgeLayersForward(self) -> list[list[tuple[vertex, vertex]]]:
        ...
    def getGraphVertices(self) -> list[vertex]:
        ...
    def getLayers(self) -> list[Layer]:
        ...
    def getPathLength(self) -> float:
        ...
    def getSearchTime(self) -> float:
        ...
    def getTotalRotation(self) -> float:
        ...
    def getTotalTime(self) -> float:
        ...
    def setWeight(self, euclideanWeight: typing.SupportsFloat, rotationalWeight: typing.SupportsFloat) -> None:
        ...
    def shortestPath(self, start: vertex, goal: vertex, interpolationDensity: typing.SupportsInt = 0, unwrap: bool = True) -> list[vertex]:
        ...
    def verticalDecomposition(self) -> list[polygon]:
        ...
class vertex:
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: vertex) -> vertex:
        ...
    def __eq__(self, arg0: vertex) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat, y: typing.SupportsFloat, theta_lb: typing.SupportsFloat, theta_ub: typing.SupportsFloat, theta: typing.SupportsFloat) -> None:
        """
        Constructor with all parameters
        """
    def __lt__(self, arg0: vertex) -> bool:
        ...
    def __ne__(self, arg0: vertex) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def dist(self, arg0: vertex) -> float:
        ...
    def getCoord(self) -> tuple[float, float]:
        ...
    def getTheta(self) -> float:
        ...
    def getThetaLb(self) -> float:
        ...
    def getThetaUb(self) -> float:
        ...
    def getX(self) -> float:
        ...
    def getY(self) -> float:
        ...
    def hasTheta(self) -> bool:
        ...
    def hash(self) -> int:
        ...
    def rotationalDist(self, arg0: vertex) -> float:
        ...
    def setBounds(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...
    def setPos(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...
    def setTheta(self, arg0: typing.SupportsFloat) -> None:
        ...
def add(arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> int:
    """
    A function that adds two numbers
    """
def get_boundary(arg0: str) -> polygon:
    """
    Get the boundary polygon from XML
    """
def get_goal(arg0: str) -> vertex:
    """
    Get the goal vertex from XML
    """
def get_map(arg0: typing.SupportsInt) -> polygon:
    """
    Generate a map polygon of a given size
    """
def get_obstacles(arg0: str) -> list[polygon]:
    """
    Get the obstacles polygons from XML
    """
def get_robot(arg0: str) -> polygon:
    """
    Get the robot polygon from XML
    """
def get_start(arg0: str) -> vertex:
    """
    Get the start vertex from XML
    """
