"""
pybind11 example plugin
"""
from __future__ import annotations
import typing
__all__ = ['Layer', 'TwoTuple', 'add', 'get_boundary', 'get_goal', 'get_map', 'get_obstacles', 'get_robot', 'get_start', 'polygon', 'vertex', 'visibility_graph']
class Layer:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, theta_lb: float, theta_ub: float, roundUpTheta: float, fineApprox: bool, hashWithTheta: bool, simplifiedGeometry: bool) -> None:
        ...
    @typing.overload
    def __init__(self, layer: Layer) -> None:
        ...
    def borderIsHole(self) -> bool:
        ...
    def buildVisibilityGraph(self, robot: polygon, border: polygon, obstacles: list[polygon]) -> None:
        ...
    def getEdges(self) -> list[tuple[vertex, vertex]]:
        ...
    def getGrownObs(self) -> list[polygon]:
        ...
    def getHoles(self) -> list[polygon]:
        ...
    def getNeighbor(self, v: vertex) -> tuple[..., ...]:
        ...
    def getRobotBBox(self) -> polygon:
        ...
    def getRobotBBoxInverted(self) -> polygon:
        ...
    def getShrinkedBorder(self) -> polygon:
        ...
    def getThetaLb(self) -> float:
        ...
    def getThetaUb(self) -> float:
        ...
    def getVertex(self, index: int) -> vertex:
        ...
    def getVisibleArea(self, v: vertex) -> ...:
        ...
    def getVisibleAreaPolygon(self, x: float, y: float) -> polygon:
        ...
    def getVisibleAreaPolygons(self) -> dict[vertex, polygon]:
        ...
    def hasHoles(self) -> bool:
        ...
    def isFeasible(self) -> bool:
        ...
    def isVertexOnHole(self, vertex: vertex) -> bool:
        ...
    def legalConfig(self, v: vertex) -> bool:
        ...
class TwoTuple:
    __hash__: typing.ClassVar[None] = None
    first: float
    second: float
    def __eq__(self, arg0: TwoTuple) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
class polygon:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: polygon) -> bool:
        ...
    def __getitem__(self, arg0: int) -> vertex:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vertices: list[vertex], sortVertices: bool, center: vertex) -> None:
        ...
    @typing.overload
    def __init__(self, vertices: list[vertex], sortVertices: bool) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: polygon) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: ..., std: ..., std: ...) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: ..., std: ..., std: ..., arg1: vertex) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: int) -> vertex:
        ...
    def bbox(self) -> polygon:
        ...
    def contains(self, arg0: vertex) -> bool:
        ...
    def convexDecomposition(self) -> list[polygon]:
        ...
    @typing.overload
    def draw(self, arg0: ..., std: ..., std: ..., CGAL: ..., std: ..., std: ..., CGAL: ...) -> None:
        ...
    @typing.overload
    def draw(self) -> None:
        ...
    @typing.overload
    def draw(self, arg0: str, arg1: str, arg2: bool) -> None:
        ...
    @typing.overload
    def draw(self, arg0: str, arg1: bool) -> str:
        ...
    def getCentroid(self) -> vertex:
        ...
    def getClockWise(self) -> ...:
        ...
    def getComplement(self) -> ...:
        ...
    def getCounterClockWise(self) -> ...:
        ...
    def getPolygon(self) -> ...:
        ...
    def getVertices(self) -> list[vertex]:
        ...
    def getX(self) -> list[float]:
        ...
    def getY(self) -> list[float]:
        ...
    def intersects(self, arg0: polygon) -> bool:
        ...
    def intersectsEdge(self, arg0: ...) -> bool:
        ...
    def invert(self) -> None:
        ...
    def isConvex(self) -> bool:
        ...
    def merge(self, arg0: polygon) -> polygon:
        ...
    def moveTo(self, arg0: float, arg1: float, arg2: float) -> None:
        ...
    def moveToCopy(self, arg0: float, arg1: float, arg2: float) -> polygon:
        ...
    @typing.overload
    def rotate(self, arg0: float) -> None:
        ...
    @typing.overload
    def rotate(self, arg0: float, arg1: vertex) -> None:
        ...
    def rotateCGALCopy(self, arg0: float) -> ...:
        ...
    @typing.overload
    def rotateCopy(self, arg0: float) -> polygon:
        ...
    @typing.overload
    def rotateCopy(self, arg0: float, arg1: vertex) -> polygon:
        ...
    def scale(self, arg0: float) -> polygon:
        ...
    def size(self) -> int:
        ...
    def translate(self, arg0: float, arg1: float) -> None:
        ...
class vertex:
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: vertex) -> vertex:
        ...
    def __eq__(self, arg0: vertex) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float) -> None:
        ...
    @typing.overload
    def __init__(self, x: float, y: float, theta_lb: float, theta_ub: float, theta: float, roundUpTheta: float, hashWithTheta: bool) -> None:
        """
        Constructor with all parameters
        """
    def __lt__(self, arg0: vertex) -> bool:
        ...
    def __ne__(self, arg0: vertex) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def dist(self, arg0: vertex) -> float:
        ...
    def getCoord(self) -> tuple[float, float]:
        ...
    def getPoint(self) -> ...:
        ...
    def getTheta(self) -> float:
        ...
    def getThetaLb(self) -> float:
        ...
    def getThetaUb(self) -> float:
        ...
    def getX(self) -> float:
        ...
    def getY(self) -> float:
        ...
    def hasTheta(self) -> bool:
        ...
    def hash(self) -> int:
        ...
    def hashWithTheta(self) -> bool:
        ...
    def mergeThetaRange(self, arg0: vertex) -> vertex:
        ...
    def rotationalDist(self, arg0: vertex) -> float:
        ...
    def setBounds(self, arg0: float, arg1: float) -> None:
        ...
    def setPos(self, arg0: float, arg1: float) -> None:
        ...
    def setTheta(self, arg0: float) -> None:
        ...
class visibility_graph:
    def __init__(self, robot: polygon, border: polygon, obstacles: list[polygon], resolution: int, considerSymmetry: bool, hashWithTheta: bool, fineApprox: bool, numThreads: int, optimal: bool = False, verbose: bool = False) -> None:
        """
        Constructs a VisibilityGraph with the specified parameters.
        """
    def animation(self, figPath: str, title: bool = True) -> None:
        ...
    def debugMaxPropagation(self) -> None:
        ...
    def draw(self, figPath: str, title: bool = True, path: bool = True, graph: bool = True, show: bool = False) -> None:
        ...
    def getAdjacentVertices(self, v: vertex) -> list[vertex]:
        ...
    def getBuildTime(self) -> float:
        ...
    def getEdgeLayersBackward(self) -> list[list[tuple[vertex, vertex]]]:
        ...
    def getEdgeLayersForward(self) -> list[list[tuple[vertex, vertex]]]:
        ...
    def getGraphVertices(self) -> list[vertex]:
        ...
    def getLayers(self) -> list[Layer]:
        ...
    def getPathLength(self) -> float:
        ...
    def getSearchTime(self) -> float:
        ...
    def getTotalRotation(self) -> float:
        ...
    def getTotalTime(self) -> float:
        ...
    def setWeight(self, euclideanWeight: float, rotationalWeight: float) -> None:
        ...
    def shortestPath(self, start: vertex, end: vertex, interpolationDensity: int = 0, unwrap: bool = True) -> list[vertex]:
        ...
    def verticalDecomposition(self) -> list[polygon]:
        ...
def add(arg0: int, arg1: int) -> int:
    """
    A function that adds two numbers
    """
def get_boundary(arg0: str) -> polygon:
    """
    Get the boundary polygon from XML
    """
def get_goal(arg0: str) -> vertex:
    """
    Get the goal vertex from XML
    """
def get_map(arg0: int) -> polygon:
    """
    Generate a map polygon of a given size
    """
def get_obstacles(arg0: str) -> list[polygon]:
    """
    Get the obstacles polygons from XML
    """
def get_robot(arg0: str) -> polygon:
    """
    Get the robot polygon from XML
    """
def get_start(arg0: str) -> vertex:
    """
    Get the start vertex from XML
    """
