IF(NOT pybind11_FOUND)
SET(pybind11_DIR "extern/pybind11")
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND mkdir pybind11-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    EXECUTE_PROCESS(COMMAND cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build
            -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}
            ${PROJECT_SOURCE_DIR}/${pybind11_DIR}
             WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make install -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make check -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build)
ENDIF()

MESSAGE(STATUS "pybind11 build directory: ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build")
SET(pybind11_DIR ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build/share/cmake/pybind11)
FIND_PACKAGE(pybind11 CONFIG REQUIRED PATHS ${PROJECT_BINARY_DIR}/pybind11-${CMAKE_BUILD_TYPE}_build)

ENDIF(NOT pybind11_FOUND)