IF(NOT CGAL_FOUND)
SET(CGAL_DIR "extern/CGAL")
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND mkdir CGAL-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    EXECUTE_PROCESS(COMMAND cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build
            ${PROJECT_SOURCE_DIR}/${CGAL_DIR}
             WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make install WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build)
ENDIF()

MESSAGE(STATUS "CGAL build directory: ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build")
FIND_PATH(
        CGAL_INCLUDE_DIR
        NAMES CGAL/basic.h
        NO_DEFAULT_PATH
        PATHS ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build/include
)

IF(CGAL_INCLUDE_DIR)
    MESSAGE(STATUS "CGAL found @ ${CGAL_INCLUDE_DIR}")
    SET(CGAL_INCLUDE_DIRS ${CGAL_INCLUDE_DIR})
    SET(CGAL_FOUND TRUE)
    SET(CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE TRUE)
    SET(CGAL_DIR ${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build/lib/cmake)
    INCLUDE(${PROJECT_BINARY_DIR}/CGAL-${CMAKE_BUILD_TYPE}_build/lib/cmake/CGAL/CGALConfig.cmake)
ELSE()
    MESSAGE(FATAL_ERROR "CGAL not found")
ENDIF()
MARK_AS_ADVANCED(CGAL_FOUND)
MARK_AS_ADVANCED(CGAL_INCLUDE_DIR CGAL_INCLUDE_DIRS)
MARK_AS_ADVANCED(CGAL_DIR)

ENDIF(NOT CGAL_FOUND)