IF(NOT Tracy_FOUND)
SET(Tracy_DIR "extern/tracy")
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND mkdir Tracy-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    EXECUTE_PROCESS(COMMAND cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build
            ${PROJECT_SOURCE_DIR}/${Tracy_DIR}
             WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make install -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)
ENDIF()

MESSAGE(STATUS "Tracy build directory: ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build")
SET(Tracy_BUILD_DIR ${PROJECT_BINARY_DIR}/Tracy-${CMAKE_BUILD_TYPE}_build)

FIND_PATH(
        Tracy_INCLUDE_DIR
        NAMES Tracy.hpp
        NO_DEFAULT_PATH
        PATHS ${Tracy_BUILD_DIR}/include/tracy/
)

FIND_LIBRARY(
        Tracy_LIBRARY
        NAMES TracyClient
        NO_DEFAULT_PATH
        PATHS ${Tracy_BUILD_DIR}/lib/
)

IF(Tracy_INCLUDE_DIR AND Tracy_LIBRARY)
    MESSAGE(STATUS "Tracy found @ ${Tracy_INCLUDE_DIR}")
    SET(Tracy_INCLUDE_DIRS ${Tracy_INCLUDE_DIR})
    SET(Tracy_LIBRARIES ${Tracy_LIBRARY})
    SET(Tracy_FOUND TRUE)
    INCLUDE(${Tracy_BUILD_DIR}/TracyConfig.cmake)
ELSE()
    MESSAGE(FATAL_ERROR "Tracy not found")
ENDIF()
MARK_AS_ADVANCED(Tracy_FOUND)
MARK_AS_ADVANCED(Tracy_INCLUDE_DIR Tracy_INCLUDE_DIRS)
MARK_AS_ADVANCED(Tracy_DIR)

ENDIF(NOT Tracy_FOUND)