IF(NOT OMPL_FOUND)
SET(OMPL_DIR "extern/ompl")
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND mkdir OMPL-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
    EXECUTE_PROCESS(COMMAND cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build
            ${PROJECT_SOURCE_DIR}/${OMPL_DIR}
             WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build)
    EXECUTE_PROCESS(COMMAND make install -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build)
ENDIF()

MESSAGE(STATUS "OMPL build directory: ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build")
SET(OMPL_BUILD_DIR ${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build)

FIND_PATH(
        OMPL_INCLUDE_DIR
        NAMES ompl/config.h
        NO_DEFAULT_PATH
        PATHS ${OMPL_BUILD_DIR}/include/ompl-1.6/
)

FIND_LIBRARY(
        OMPL_LIBRARY
        NAMES ompl
        NO_DEFAULT_PATH
        PATHS ${OMPL_BUILD_DIR}/share/
)

IF(OMPL_INCLUDE_DIR AND OMPL_LIBRARY)
    MESSAGE(STATUS "OMPL found @ ${OMPL_INCLUDE_DIR}")
    SET(OMPL_INCLUDE_DIRS ${OMPL_INCLUDE_DIR})
    SET(OMPL_LIBRARIES ${OMPL_LIBRARY})
    SET(OMPL_FOUND TRUE)
    INCLUDE(${OMPL_BUILD_DIR}/omplConfig.cmake)
ELSE()
    MESSAGE(FATAL_ERROR "OMPL not found")
ENDIF()
MARK_AS_ADVANCED(OMPL_FOUND)
MARK_AS_ADVANCED(OMPL_INCLUDE_DIR OMPL_INCLUDE_DIRS)
MARK_AS_ADVANCED(OMPL_DIR)

ENDIF(NOT OMPL_FOUND)