IF (NOT GLAD_FOUND)
    SET(GLAD_DIR "extern/glad")
    IF (NOT EXISTS ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build)
        EXECUTE_PROCESS(COMMAND mkdir GLAD-${CMAKE_BUILD_TYPE}_build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
        EXECUTE_PROCESS(COMMAND cmake
                -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build
                ${PROJECT_SOURCE_DIR}/${GLAD_DIR}
                WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build)
        EXECUTE_PROCESS(COMMAND make install -j 30 WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build)
    ENDIF ()

    MESSAGE(STATUS "GLAD build directory: ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build")
    FIND_PATH(
            GLAD_INCLUDE_DIR
            NAMES matplot/matplot.h
            NO_DEFAULT_PATH
            PATHS ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build/include
    )

    FIND_LIBRARY(
            GLAD_LIBRARY
            NAMES matplot
            NO_DEFAULT_PATH
            PATHS ${PROJECT_BINARY_DIR}/GLAD-${CMAKE_BUILD_TYPE}_build/lib
            NO_CACHE
    )

    MESSAGE(STATUS "GLAD found @ ${GLAD_INCLUDE_DIR}")
    MESSAGE(STATUS "GLAD found @ ${GLAD_LIBRARY}")
    IF (GLAD_INCLUDE_DIR AND GLAD_LIBRARY)
        SET(GLAD_INCLUDE_DIRS ${GLAD_INCLUDE_DIR})
        SET(GLAD_LIBRARIES ${GLAD_LIBRARY})
        SET(GLAD_FOUND TRUE)
    ELSE ()
        MESSAGE(FATAL_ERROR "GLAD not found")
    ENDIF ()
    MARK_AS_ADVANCED(GLAD_FOUND)
    MARK_AS_ADVANCED(GLAD_INCLUDE_DIR GLAD_INCLUDE_DIRS)
    MARK_AS_ADVANCED(GLAD_LIBRARY GLAD_LIBRARIES)

ENDIF (NOT GLAD_FOUND)
